export const Languages =  {

    uz: {
        employees: 'Xodimlar',
        fio:'F.I.O',
        position: 'Lavozim',
        login: 'Login',
        color: 'Rangi',
        serial_number: 'Tartib raqami',
        actions: 'Xarakatlar',
        create: "Qo'shish",
        decrease: 'Kamayish',
        growth: "O'sish",
        name: 'Ism',
        add_employee: "Xodim Qo'shish",
        employee_roles: 'Xodim ruxsatlari',
        employee_name: 'Xodimning ismi',
        Position_employee: 'Xodimning lavozimi',
        password: 'Parol',
        Determination__salary: "Oylik maosh uchun foiz belgilash",
        Fixed_salary: 'O`zgarmas oylik maosh',
        Serial_number: "Tartib raqami",
        reset_password: 'Parolni takrorlang',
        image: 'Rasmi',
        show: "Ko'rish",
        edit_password: "Parolni o'zgartirish",
        services: 'Xizmatlar',
        price: 'Narxi',
        material_price: 'Material narxi',
        technic_price: 'Texnik narxi',
        name_content: 'Nomi',
        code: 'Kodi',
        status: 'Holati',
        category: 'Kategoriyasi',
        personal_procent: 'Xodimlar uchun shaxsiy ulushlar taqsimlash',
        percentage: 'Foiz',
        service_types: 'Xizmat turlari',
        update: 'Tahrirlash',
        Patients: 'Bemorlar',
        last_name: 'Familiya',
        phone: 'Telefon',
        Date_birth: "Tug'ulgan sana",
        Payment_status: "To'lov holati",
        Register_time: 'Ro\'yxatga olingan vaqti',
        Concomitant_diseases: "Yo'ldosh kasalliklar",
        Job: 'Kasbi',
        CategoryDiseases: "Yo'ldosh kasalliklar",
        diseases: 'Kasalliklar',
        Address: 'Manzil',
        Gender: 'Jinsi',
        Male: 'Erkak',
        Woman: 'Ayol',
        Created_at: 'Saqlangan vaqti',
        Updated_at: 'O\'zgartirilgan vaqti',
        AddDoctor: 'Doktorga biriktrish',
        Doctor: 'Shifokor',
        ReceptionTime: 'Qabul vaqti',
        Classification: 'Tasnif',
        Duration: 'Davomiyligi',
        Summa: 'Miqdori',
        summError: "Taqsimlanayotgan summa xizmat narxidan oshib ketmasligi kerak",
        Treatmetns: 'Davolanishlar',
        TreatmentStarted_at: 'Davolash sanasi',
        New: 'Yangi',
        DoctorFinished: 'Doktor tomonidan tugatildi',
        Finished: 'Tugatildi',
        Unpaint: "To'lanmagan",
        NotFullPaint: "To'liq to'lanmagan",
        Closed: "Yopilgan",
        PatientEndPayment: "Bemorning oxirgi to'lovi",
        AmountOwed: 'Qarzdorlik summasi',
        PaymentAmount: 'To\'lov summasi',
        AmountOwedType: "Bemorning oxirgi to'lov turi",
        Payments: "To'lovlar",
        PaymentTypes: "To'lov turlari",
        DebtTreatments: "Qarzdor davolanishlar",
        EmployeeReports: "Xodimlar hisobotlar",
        PayingEmployees: "Xodimlarga pul berish",
        DailyExpenses: "Kunlik xarajatlar",
        Reports: "Hisobotlar",
        Amount: "Miqdori",
        Type: "Turi",
        ServicesUsed: "Foydalanilgan xizmatlar",
        AmountPaid: "To'langan summa ",
        Indebtedness: "Qarzdorliklar",
        Balans: 'Balans',
        PatientAbout: 'Bemor haqida',
        NotFound: "topilmadi",
        Finished_at: "Tugash vaqti",
        Treatment: 'Davolash',
        Warehouse: 'Ombor',
        Filials: 'Filiallar',
        Filial: 'Filial',
        Categories: 'Categoriyalar',
        Groups: 'Guruxlar',
        Group: 'Gurux',
        Products: 'Mahsulotlar',
        Measure: "O'lchovi",
        TheRest: 'Qolgan',
        TotalAmount: 'Jami summa',
        MinSize: 'Miqdor qolganda xabar berilsin',
        Bar_code: 'Shtrix codi',
        WendorCode: 'Sotuvchi codi',
        SizeType: "O'lchov birligi",
        Piece: 'dona',
        Liter: 'litr',
        Kilogram: 'kilogramm',
        Gram: 'garmm',
        Documents: 'Hujjatlar',
        Collection: "To'plamlar",
        Suppliers: 'Yetkazib beruvchilar',
        Supplier: 'Yetkazib beruvchi',
        Search: 'Izlash',
        Bin: 'Bin',
        Email: 'Email',
        ContactPerson: 'Bog\'lanish uchun shaxs',
        BankDetails: 'Bank rekzividlari',
        Description: "Izoh",
        CreatedUser: 'Yaratdi',
        AddProduct: "Mahsulotlarni ro'yxatga olish",
        Save: "Saqlash",
        notSaved: "Saqlanmagan",
        addService: "Xizmat qo'shish",
        ServiceCount: "Xizmat soni",
        PaymentError: "To\'lov miqdori ortib ketmasligi kerak ",
        DebitTitle: "Qarzga kim tomonidan ruxsat berildi?",
        DebitData: 'Qaytarish sanasi',
        PolyClinic: 'Shifoxona',
        TreatmentPrice: 'Davolanish narxi',
        PaymentsUser: "Bemorning jami to'lovi",
        PaymentSum: "To'lanishi kerak",
        Discount: 'Chegirma',
        DiscountError: "To'lanshi kerak bo'lgan miqdordan ortib ketmasligi kerak",
        Welcome: "Hush kelibsiz !",
        TitleCheck: 'Bizni tanlaganingiz uchun raxmat !',
        Date: 'Sana',
        Service_name: 'Xizmat nomi',
        TotalSum: 'Umumiy summa',
        Material_total_sum: "Xom ashyo summasi",
        Doctor_total_sum: "Shifokor summasi",
        DiscountSend: 'Chegirma berildi',
        Payment: "To'lov",
        Paid: "To'landi",
        Indebtednes: 'Qarzdorlik',
        ProductNot: 'Omborda mahsulot qolmagan',
        ProductMin: 'Omborda mahsulot yetarli emas',
        NotLimited: 'Cheklanmagan',
    },
    ru:{
        NotLimited: 'Не ограничен',
        ProductMin: 'На складе недостаточно товара',
        ProductNot: 'На складе не осталось товаров',
        Indebtednes: 'Задолженность',
        Paid: "Оплаченный",
        Payment: "Оплата",
        DiscountSend: "Была предоставлена ​​скидка",
        Doctor_total_sum: "Сумма доктора",
        Material_total_sum: "Количество сырья",
        TotalSum: 'Общая сумма',
        Service_name: 'Наименование услуги',
        Date: 'Дата',
        TitleCheck: 'Спасибо, что выбрали нас!',
        Welcome: "Добро пожаловать !",
        DiscountError: "Не должна превышать сумму к оплате",
        Discount: 'Скидка',
        PaymentSum: "Должно быть оплачено",
        PaymentsUser: "Общая плата за пациента",
        TreatmentPrice: 'Cost of treatment',
        PolyClinic: 'Больница',
        DebitData: 'Дата возврата',
        DebitTitle: "Кто разрешил получение кредита?",
        PaymentError: "Сумма платежа не должна увеличиваться ",
        ServiceCount: "Сервисный номер",
        addService: "Добавить услугу",
        notSaved: "Не сохранено",
        Save: "Сохранять",
        AddProduct: "Регистрация продукта",
        Supplier: 'Поставщик',
        CreatedUser: 'Создать ',
        Description: "Описание",
        BankDetails: 'Банковские реквизиты',
        ContactPerson: 'Контактное лицо',
        Email: 'Электронная почта',
        Bin: 'Бин',
        Search: 'Поиск',
        Suppliers: 'Поставщики',
        Collection: "Комплекты",
        Documents: 'Документы',
        Gram: 'грамм',
        Kilogram: 'килограмм',
        Liter: 'литр',
        Piece: 'кусок',
        Bar_code: "Штрих-код",
        WendorCode: 'Код продавца',
        SizeType: "Единица измерения",
        Products: 'Продукты',
        MinSize: 'Уведомлять при остатки ',
        TotalAmount: 'Общая сумма',
        Мера: "Мера",
        TheRest: 'Остальные',

        Finished_at: "Время окончания",
        Treatment: 'Уход',
        NotFound: "не найдено",
        employees: 'Cотрудники',
        fio:'Ф.И.О.',
        position: 'Позиция',
        login: 'Aвторизоваться',
        color:'Цвет',
        serial_number: 'Серийный номер',
        actions: 'Действия',
        create: "Добавлять",
        decrease: 'Снижаться',
        growth: 'Рост',
        name: 'Имя',
        add_employee: 'Добавить сотрудника',
        employee_roles:'Разрешения сотрудников',
        Groups: 'Группы',
        Group: 'Группа',
        employee_name: 'Имя сотрудника',
        Position_employee: 'Должность сотрудника',
        password: 'Пароль',
        Determination__salary: "Определение процентов к ежемесячной зарплате",
        Fixed_salary: 'Фиксированная ежемесячная зарплата',
        Serial_number: "Серийный номер",
        reset_password: 'Повторите пароль',
        image: 'Фото',
        show: "Видеть",
        edit_password: "Изменить пароль",
        services: 'Услуги',

        price: 'Цена',
        material_price: 'Цена материала',
        technic_price: 'Техническая цена',
        name_content: 'Имя',
        code: 'Коди',
        status: 'Положение дел',
        category: 'Категория',
        personal_procent: 'Распределение личных льгот для сотрудников',
        percentage: 'Процент',
        service_types: 'Типы услуг',
        update: 'Редактирование',
        Patients: 'Пациенты',
        last_name: 'Фамилия',
        Categories: 'Категории',

        phone: 'Tелефон',
        Date_birth: 'Дата рождения',
        Payment_status: 'Статус платежа',
        Register_time: 'Зарегистрированное время',
        Concomitant_diseases: 'Сопутствующие заболевания',
        Job: 'Работа',
        diseases: 'Болезни',
        CategoryDiseases: 'Сопутствующие заболевания',
        Address: 'Адрес',
        Gender: 'Пол',
        Male: 'Мужской',
        Woman: 'Девушка',
        Created_at: 'Сэкономленное время',
        Updated_at: 'Изменено время',
        AddDoctor: 'Привязанность к доктору',
        Doctor: 'Врач',
        ReceptionTime: 'Время приема',
        PatientAbout: 'О пациенте',

        Classification: 'Классификация',
        Duration: 'Продолжительность',
        Summa: 'Количество',
        summError: "Сумма, подлежащая распределению, не должна превышать цену услуги",
        Treatmetns: 'Лечение',
        TreatmentStarted_at: 'Дата лечения',
        New: 'Новый',
        DoctorFinished: 'Завершено доктором',
        Finished: 'Законченный',
        Unpaint: 'Неоплачиваемый',
        NotFullPaint: 'Оплачено не полностью',
        Closed: 'Закрыто',
        PatientEndPayment: "Последний платеж пациента",
        AmountOwed: 'Причитающаяся сумма',
        AmountOwedType: "Последний вид оплаты пациента",
        PaymentAmount: 'К оплате',
        Payments: "Платежи",
        PaymentTypes: "Виды оплаты",
        DebtTreatments: "Лечение долга",
        EmployeeReports: "Отчеты сотрудников",
        PayingEmployees: "Оплата сотрудников",
        DailyExpenses: "Ежедневные расходы",
        Reports: "Отчеты",
        Amount: "Количество",
        Type: "Тип",
        ServicesUsed: "Используемые услуги",
        AmountPaid: "Оплаченная сумма",
        Indebtedness: "Задолженность",
        Balans: 'Баланс',
        Warehouse: 'Склад',
        Filials: 'Ветви',
        Filial: 'Ветвь',

    }

}

