export const Languages =  {

    uz: {
        employees: 'Xodimlar',
        fio:'F.I.O',
        position: 'Lavozim',
        login: 'Login',
        color: 'Rangi',
        serial_number: 'Tartib raqami',
        actions: 'Xarakatlar',
        create: "Qo'shish",
        decrease: 'Kamayish',
        growth: "O'sish",
        name: 'Ism',
        add_employee: "Xodim Qo'shish",
        employee_roles: 'Xodim ruxsatlari',
        employee_name: 'Xodimning ismi',
        Position_employee: 'Xodimning lavozimi',
        password: 'Parol',
        Determination__salary: "Oylik maosh uchun foiz belgilash",
        Fixed_salary: 'O`zgarmas oylik maosh',
        Serial_number: "Tartib raqami",
        reset_password: 'Parolni takrorlang',
        image: 'Rasmi',
        show: "Ko'rish",
        edit_password: "Parolni o'zgartirish",
        services: 'Xizmatlar',
        price: 'Narxi',
        material_price: 'Material narxi',
        technic_price: 'Texnik narxi',
        name_content: 'Nomi',
        code: 'Kodi',
        status: 'Holati',
        category: 'Kategoriyasi',
        personal_procent: 'Xodimlar uchun shaxsiy ulushlar taqsimlash',
        percentage: 'Foiz',
        service_types: 'Xizmat turlari',
        update: 'Tahrirlash',
        Patients: 'Bemorlar',
        last_name: 'Familiya',
        phone: 'Telefon',
        Date_birth: "Tug'ulgan sana",
        Payment_status: "To'lov holati",
        Register_time: 'Ro\'yxatga olingan vaqti',
        Concomitant_diseases: "Yo'ldosh kasalliklar",
        Job: 'Kasbi',
        CategoryDiseases: "Yo'ldosh kasalliklar",
        diseases: 'Kasalliklar',
        Address: 'Manzil',
        Gender: 'Jinsi',

    },
    ru:{
        employees: 'Cотрудники',
        fio:'Ф.И.О.',
        position: 'Позиция',
        login: 'Aвторизоваться',
        color:'Цвет',
        serial_number: 'Серийный номер',
        actions: 'Действия',
        create: "Добавлять",
        decrease: 'Снижаться',
        growth: 'Рост',
        name: 'Имя',
        add_employee: 'Добавить сотрудника',
        employee_roles:'Разрешения сотрудников',
        employee_name: 'Имя сотрудника',
        Position_employee: 'Должность сотрудника',
        password: 'Пароль',
        Determination__salary: "Определение процентов к ежемесячной зарплате",
        Fixed_salary: 'Фиксированная ежемесячная зарплата',
        Serial_number: "Серийный номер",
        reset_password: 'Повторите пароль',
        image: 'Фото',
        show: "Видеть",
        edit_password: "Изменить пароль",
        services: 'Услуги',

        price: 'Цена',
        material_price: 'Цена материала',
        technic_price: 'Техническая цена',
        name_content: 'Имя',
        code: 'Коди',
        status: 'Положение дел',
        category: 'Категория',
        personal_procent: 'Распределение личных льгот для сотрудников',
        percentage: 'Процент',
        service_types: 'Типы услуг',
        update: 'Редактирование',
        Patients: 'Пациенты',
        last_name: 'Фамилия',
        phone: 'Tелефон',
        Date_birth: 'Дата рождения',
        Payment_status: 'Статус платежа',
        Register_time: 'Зарегистрированное время',
        Concomitant_diseases: 'Сопутствующие заболевания',
        Job: 'Работа',
        diseases: 'Болезни',
        CategoryDiseases: 'Сопутствующие заболевания',
        Address: 'Адрес',
        Gender: 'Пол',


    }

}

